Sprint 7 solution in file manager
GlusHHiv/java-kanban pull request #2
Opened 2024-04-08 15:49 UTC by GlusHHiv

2024-04-09 10:05 UTC, TomattmanYandex requested changes
Комменты в коде

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
так как InMemoryTaskManager уже имплементит TaskManager
тут нам не обязательно указывать что файловый менеджер так же имплементит TaskManager

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                if (ids.isEmpty()) {
а зачем это?

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                for (Integer i : ids) {
все еще не понятно зачем это?
почему не сделать 3 цикла, чтобы обойти каждую мапу, и записать каждый объект в файл,

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                    }
историю тоже нужно записывать в файл

2024-04-09 10:05 UTC, TomattmanYandex commented on src/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Exception {
по условию, исключение должно быть непроверяемым

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
по условию исключение должно быть непроверяемым, и ловить его тут не надо

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        this.file = file;
по хорошему сразу бы и считать все из файла
или сделать конструктор приватным,  и позволять создавать файловый таск менеджер только через статический метод

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public  FileBackedTaskManager loadFromFile(File file1)  {
этот метод стоит сделать статическим, и тогда его можно использовать вместо конструктора

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        return new FileBackedTaskManager(file1, historyManager);
вернется новый объект не заполненный данными

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                fullLine = String.join("\n", fullLine, line);
логика не понятна,
ты считываешь файл, построчно, чтобы потом соеденитьь все строки в одну, чтобы потом снова разделить их на строки?
как сделать лучше
1) первую строку опускаем, это заголовок
2) считываем строку если она не пустая, то отдельным методом преобразуем ее в объект
3) добавляем обьект в мапу
4) если встречали ранее пустую строку и строка не пустая, то это строка с историей, превращаем ее в массив чисел, проходим по нему и добавляем из мап в историю значния

не забывай, что должны быть после этого эпики с сабтасками, и счетчик идентификаторов должные обновиться тоже

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        if (line.equals("NEW")) {
у enum есть метод преобразующий из строки в его значение

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        id = strList.size() - 1;
коммент ко всему методу целиком
1) лучше иметь отдельный класс конвертер со статическими методами, который будет переводить в нужный формат и обратно (т.е. в классе будут методы типа taskToString, epicToString, historyToString, stringToTask, stringToHistory) так для того чтобы изменить формат тебе понядобится новый класс с теми же методами, и все, просто используешь его вместо него
2) сабтаск может быть считан из файла до того как считан эпик, и тогда добавление гео эпику выкинет ошибку, следовательно, сначала все считываем и только потом соединяем

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public String readFile() {
этот метод должен быть приватным

2024-04-09 10:05 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public String readFile() {
да и зачем этот метод?

2024-04-09 10:05 UTC, TomattmanYandex commented on src/model/Epic.java
> +        return TaskTypes.EPIC +  "," + getName() + "," + getStatus() + "," + getDescription() + "\n";
метод toString возвращает строковое представление обьекта, а не трансформирует его в специаольный формат, 
что будет если будет второй способ хранения данных, не сможет у класса быть два метода toString
как этио лучше организовать я написал где то в файловом таск менеджере

2024-04-10 11:50 UTC, GlusHHiv commented on src/managers/task/FileBackedTaskManager.java
> +                if (ids.isEmpty()) {
чтобы id шли по порядку

2024-04-11 08:09 UTC, TomattmanYandex requested changes
Привет, что то еще актуально с прошлой проверки, что то новое добавил

2024-04-11 08:09 UTC, TomattmanYandex commented on src/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Error {
мы наследуемся либо от Exception либо от RUntimeException либо от их наследников
Класс Error существует для ошибок виртуальной машины, и лучше его не использовать

2024-04-11 08:09 UTC, TomattmanYandex commented on src/convertors/Convertor.java
> +    public static String convertHistory(List<Task> history) {
тут бы еще добавить методы на преобразование из строки в объекты
так получится что только в этом классе будет ответственность за формат данных в файле

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                if (ids.isEmpty()) {
А зачем? ну да ладно это не критично

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                        writer.write(i + "," + Convertor.convertSubtaskToString(subtasks.get(i)));
прошлый раз не заметил, но идентификатор это часть объекта который мы записываем, и следовательно часть формата, и добавлять это стоит там же где и остальные поля

сейчас получается, что часть формата в одном месте часть в другом, поддерживать такое будет тяжело

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
этот комментарий все еще актуален

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        this.file = file;
это все еще актуально

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public  FileBackedTaskManager loadFromFile(File file1)  {
по условию метод должен быть статическим

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +            System.out.println("Ошибка чтения");
и тут должны пробрасывать наше собственное непроверяемое  исключение

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        return new FileBackedTaskManager(file1, historyManager);
все еще актуально

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public String readFile() { //для тестов
метод должен быть приватным

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public String readFile() { //для тестов
если это для тестов, то должно быть в тестах

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    private Task convertStringToTaskAndLoad(String line) {
конвертирование стоит вынести в конвертер

2024-04-11 08:09 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    private void convertHistoryFromStringAndAdd(String line) {
и этот метод тоже

2024-04-11 08:09 UTC, TomattmanYandex commented on src/model/Epic.java
> +    private final  TaskTypes type = TaskTypes.EPIC;
енамы лучше называть как единственный объект, так как он представляет собой именно один обьект из набора
вместо TaskTypes - TaskType

2024-04-11 08:09 UTC, TomattmanYandex commented on src/model/TaskTypes.java
> +public enum TaskTypes {
Лучше называть TaskType

2024-04-12 11:23 UTC, TomattmanYandex requested changes
Привет, многие моменты еще надо исправить, некоторые коменты вообще были проигнорированы, 

Если есть вопросы, пиши в чате

2024-04-12 11:23 UTC, TomattmanYandex commented on src/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Exception {
непроверяемые это те которые наследуются от RuntimeException
Способ проверить простой, если там где ты ее используешь ide просит добавить try catch Или throws значит оно проверяемое инче непроверяемое

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
и все еще актуально

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file1)  {
прекрасно)

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                    if (Convertor.convertStringToTaskAndLoad(line)
а, зачем, почему, вообще непонятно откуда взявший таск и сравнение
ЗАчем?

2024-04-12 11:23 UTC, TomattmanYandex commented on src/convertors/Convertor.java
> +        if (line.equals("id,type,name,status,description,epic")) {
ты создаешь, таск, который реально можно существовать, а потом его проверяешь где то, зачем? просто при считывании из файла игнорируй первую строку, считал даже не в переменную и забыл, ведь она должна быть по условию, а возврщать лучше например null тогда точно понятно что это не реальный таск

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                    if (Convertor.convertStringToTaskAndLoad(line)
понял, зачем, но это не нормально
просто перед строчкой 82 сделай buffer.readLine();
и все, первая строка игнорируется, а заголовок только в первой строке

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +    protected static final HashMap<Integer, Task> tasks = new HashMap<>();
я не знаю откуда это взялось, но эти поля не должны быть статическими, это внутреннее состояние таск менеджера, внутренне состояние объекта мы храним в обычных переменных объекта, со статическими переменными все экземпляры класса InMemoryTaskManager будут иметь одинаковые таски

Если ты создашь InMEmoryTaskManager потом fileBackedTaskManager и добавишь во второй пару тасок, они не должны быть видны не в InMemoryTaskMAnager не в других объектах FileBackedTaskManager

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        return new FileBackedTaskManager(file1, historyManager);
переменный с мапами не должны быть статическими, и это все еще актуально

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    public String readFile() { //для тестов
все еще актуально, тут не должно быть этого метода

2024-04-12 11:23 UTC, TomattmanYandex commented on src/convertors/Convertor.java
> +    public static Task convertStringToTaskAndLoad(String line) {
почему метод называется с AndLoad в конце, куда он что то загружает?

2024-04-12 11:23 UTC, TomattmanYandex commented on src/convertors/Convertor.java
> +    public static Task convertHistoryFromStringAndAdd(String line) {
AndAdd куда он что то добавляет?

2024-04-12 11:23 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +            } catch (IOException e) {
1 ) у эпиков будет пустой список сабтасков
2) счетчик идентификаторов не обновляется, при добавлении новых тасков после считывания из файла, есть шанс что старые перепишутся

2024-04-17 13:08 UTC, TomattmanYandex requested changes
Привет, есть еще каша в чтении из файла

2024-04-17 13:08 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    private void dataFilling() {
не очень хорошее имя метода, методы называют действиями, например fillData

2024-04-17 13:08 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +        } catch (ManagerSaveException managerSaveException) {
раз это непроверяемое исключение, то его ловить не обязательно, и по условию не надо

2024-04-17 13:08 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                save();
зачем ты вызываешь метод save ведь мы ничего не изменяем в состоянии, т.е. получится так, что ты только что считал все из файла, и сразу в него все записываешь

2024-04-17 13:08 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +                    }
историю следует записывать в файл в виде списка идентификаторов
может получиться так, что в истории обьекты будут в одном состоянии ,а сами обьекты будут в другом

2024-04-18 13:28 UTC, TomattmanYandex approved these changes
Принято

2024-05-26 20:49 UTC, merged