Sprint 8 solution time and duration
GlusHHiv/java-kanban pull request #3
Opened 2024-05-23 21:55 UTC by GlusHHiv

2024-05-24 08:30 UTC, TomattmanYandex requested changes
Привет
1) после каждой работы когда пулл реквест апрувнут, он должен быть смерджен, чтобы я не смотрел повторно одно и то же
следовательно тебе надо смерджить предыдущие пулл реквесты, и потом подготовить этот
2) коментарии как обычно в коде
3) тесты я пока что не смотрел, потмоу что большая часть из них уйдет после мерджа старых пулл реквестов
4) вижу очень много новой каши по структуре данных например таски не должны содержать информацию которая относится только к эпикам или сабтаскам, надо исправлять

2024-05-24 08:30 UTC, TomattmanYandex commented on Java-test.txt
> +id,type,name,status,description,epic
кажется этот файл уже не актуален, ибо должны быть время выполнения и длительность

второй момент, формат же файла csv почему расширение txt?

2024-05-24 08:30 UTC, TomattmanYandex commented on la
> +[33mcommit 95e59107f6effaae46b0b177fc31e8ef66feb92d[m[33m ([m[1;36mHEAD -> [m[1;32msprint_6-solution[m[33m)[m
а это тут зачем?

2024-05-24 08:30 UTC, TomattmanYandex commented on src/convertors/Convertor.java
> +    public static HashMap<TaskType, Task> convertStringToTask(String line) {
я бы порекомендовал сделать 3 отдельных метода, каждый из которых возвращает определенный тип обьекта и принимает строку
if (str[1].equals("TASK")) {
   map.put(TaskType.TASK,lineToTask(line))
}

2024-05-24 08:30 UTC, TomattmanYandex commented on src/convertors/Convertor.java
> +            HashMap<TaskType, Task> map = new HashMap<>();
зачем создавать целую мапу, для того чтобы вернуть один обьект?
почему просто не вернуть сам обьект

и вообще вариант как сделать лучше
1) делаем метод который по строке возвращает тип
2) в фаловом таск менеджере при считывании для каждой строки вызываем метод вовзращающий тип, и в зависимости от результата, вызываем один из трех методов, и сразу доабвляем в нужную мапу

2024-05-24 08:30 UTC, TomattmanYandex commented on src/convertors/Convertor.java
> +    public static ArrayList<Integer> convertHistoryFromString(String line) {
а где метод превращающий истроию в строку?

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/history/HistoryManager.java
> +    boolean removeFirst();
такого метода тут быть не должно?

да и вообще должны быть только методы на добавление, удаление (не первого, а конкретного таска) и метод на возвращение списка

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/history/InMemoryHistoryManager.java
> +    public void addFirst(Task task) {
этот метод не для публичного пользования как и многие другие

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/Task.java
> +    protected ArrayList<Integer> subtasks = new ArrayList<>();
что тут происходит, почему тут появились сабтаски, у таска?

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/Task.java
> +    protected Integer epicId;
почему у таска есть идентификатор эпика?

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/Task.java
> +    public Task() {
зачем такой конструктор, если он не делает ничего, и почему он добавлет имя?

можно либо просто не создавать конструктор, если он не нужен, или не делать в нем ненужных действий

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/Task.java
> +    protected LocalDateTime endTime;
у тасков не должно быть времени окончания

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/Task.java
> +    public boolean isNullTask() {
зачем этот метод?

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/Task.java
> +    public void addMinutes(Long minutes) {
у нас есть геттер и сеттер для продолжительности, остальное может быть логикой сервиса

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/Task.java
> +    public void calculateEndTime() {
для тасок этот метод должен быть getEndTime и вовзврщать время окончания

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/PersonalComparator.java
> +package model;
зачем нужен этот компаратор?

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/LinkedMapList.java
> +package model;
этот класс лучше перенести к менеджеру истории, ибо он относится именно к нему, а не к моделям

2024-05-24 08:30 UTC, TomattmanYandex commented on src/model/LinkedMapList.java
> +    public void linkLast(T data, int id) {
зачем нужны методы linkLast linkFIrst когдме можно обойтись одним методом link
ведь тогда нам перед вызовом LinkLast и linkFirst все равно придётся проверять позицию элемента

так же и с unlink

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/TaskManager.java
> +    Integer findTaskIdByName(String name);
Такого в требованиях не было, так зачем тогда добавлять

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        for (Task subtask1 : subtasks.values()) {
зачем это, у нас могут быть несколько одинаковых сабтасок
например 
есть эпики, сделать чай, сделать кофе, у обоих первыми сабтасками будет, набрать в чайник воды, вскипятить чайник, и они будут абсолютно одинаковые,
но с текущей логикой не получится их добавить

Предлагаю написать на это тест

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        if (!isEpicExist(subtask.getEpicId()) || isIntersection(subtask)) { // Проверка на наличие эпика с id: epicId
это две разные проверки, и стоит их проверять отдельно

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        addToTreeSet(epics.get(subtask.getEpicId()));
эпики мы не добавляем с сортированный список, потому что они всегда будут пересекаться по времени со своими сабтасками

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        addToTreeSet(epic);
писал выше

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +    public Task updateTask(Task task) {
при обновлении надо тоже проверять на пересечение

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +    public Task updateTask(Task task) {
и обновлять в сортированном списке

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +    public Subtask updateSubtasks(Subtask subtask) {
аналогично с таском

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        taskTreeSet.stream().filter(task -> !TaskType.TASK.equals(task.getType())).collect(Collectors.toList());
а что тут происходит?

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        taskTreeSet.stream().filter(task -> !TaskType.TASK.equals(task.getType())).collect(Collectors.toList());
надо удалить из сортированного списка

возможно эта вся оперция создаст список без этого таска, но
1) там фильтрация по типу, а не по идентификатору, следовательно будет промах
2) стримы возвращают в конце новый обьект который ку да то надо записать

на это стоит написать тест, что при удалении таска, 
1) он удаляется
2) он (и только он) удаляется  из списка приоритезированных

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        taskTreeSet.stream().filter(task -> !TaskType.SUBTASK.equals(task.getType())).collect(Collectors.toList());
и тут то же самое

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        getEpicSubtasks(epic.getId())
плохое использование стримов
стоит посчитать время выполнения всех сабтасков, и потом просетать его эпику

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        getEpicSubtasks(epic.getId())
вторая проблема, время выполнения у нас не обязательное поле, если его не будет у сабтаска, то будет ошибка

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        epic.calculateEndTime();
время окончания эпика это не временя старта + время выполнения
время окончания эпика, это времея окончания последнего сабтаска

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        if (!isIntersection(task)) {
зачем тут проверка на пересечение, проверка на пересечение должна быть при добавлении, а там если мы можем добавлять то уже добавляем везде без доп проверок

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/InMemoryTaskManager.java
> +        //System.out.println("\n Эпики : ******* \n" + epics + "\nконэц \n");
закоментированный код не допускается

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +package managers.task;
1) в этом классе даже изменений не должно быть в этом задании (так как у тебя конвертеры в отдельном классе) поэтому смотреть я его даже пока что не буду

2024-05-24 08:30 UTC, TomattmanYandex commented on src/managers/task/FileBackedTaskManager.java
> +    ArrayList<Integer> historyIds = new ArrayList<>();
но вот тут как минимум не хватает модифкаторов доступа

2024-05-26 22:01 UTC, GlusHHiv commented on src/managers/task/TaskManager.java
> +    Integer findTaskIdByName(String name);
Для собственного удобства и тестов, это нужно убрать?

2024-05-27 09:50 UTC, TomattmanYandex reviewed
Привет, я все еще вижу изменения, которых не должно быть в этом пулл реквесте
возможно после мерджа некоторые изменения не просчитались

попробуй закрыть этот пулл ревест (отменить его) а потом создать заново

2024-05-27 09:50 UTC, TomattmanYandex commented on src/managers/history/HistoryManager.java
> +    boolean removeFirst();
комментарий еще актуален

2024-05-27 09:50 UTC, TomattmanYandex commented on src/managers/history/InMemoryHistoryManager.java
> +    public void addFirst(Task task) {
почему эти изменения еще есть в этом пулл реквесте, это должно было быть выполнено в прошлом спринте, и в этом спринте никак не изменяться

2024-05-27 09:51 UTC, TomattmanYandex requested changes
случайно нажал комментировать а не запросить изменения

2024-05-29 20:20 UTC, closed without merging